### ISSUE TITLE
Mini window doesn't resize back to small after no composites error

### ISSUE THREAD

**Issue by neilenns** [vatis-project/vatis#120]
To reproduce:

1. Connect, publish an atis, and minimize to get the small window with current atis showing
2. Leave vatis connected
3. Disconnect from vrc

Result: Mini window correctly shows "No composites connected" and resizes to fit the text

<img width="243" alt="image" src="https://user-images.githubusercontent.com/9524118/230730507-1967a7ca-b878-4e40-bed3-c93dba1228f1.png">

5. Reconnect to VRC and re-publish an ATIS

Result: mini window is too wide
Expected result: Mini window resizes back to the correct size automatically

<img width="250" alt="image" src="https://user-images.githubusercontent.com/9524118/230730461-115473a4-7bc9-4db5-96ae-ffc3ab44571d.png">

**Comment by justinshannon** [comment]
This will be fixed in the next version with the restructured "mini window". The window size will be fixed (cannot be manual resized), but the height will auto-adjust based on the number of connected ATISes.

![vATIS_uvyGneLhas](https://user-images.githubusercontent.com/3221191/231905341-88e884fe-907f-462f-b9d5-31f91c57c185.png)

**Comment by neilenns** [comment]
Beautiful!

**Comment by justinshannon** [comment]
Beta 8 is now available.

**Comment by neilenns** [comment]
Wooooo!!!


________________________________

**Comment by neilenns** [comment]
Wooo!
