### ISSUE TITLE
[BUG] vATIS won't open

### ISSUE THREAD

**Issue by SpyrosTTK** [vatis-project/vatis#126]
Opened the app and it automatically procceded with the typical update to beta9.
Then I got this message:
![image](https://user-images.githubusercontent.com/79931000/233640969-a70751b9-da13-43ea-b43c-e7c99b5ce11e.png)
Of course no problem with extra dependencies, but I have downloaded the .NET version specified and it still won't let me use the app.

**Comment by justinshannon** [comment]
Try installing the "full setup" version https://github.com/vatis-project/vatis/releases/download/v4.0.0-beta.9/vATIS-Setup-4.0.0-beta.9.exe

The auto-update only updates the changed files and doesn’t include the .NET 6 framework dependencies (to reduce the download size). 

There was a breaking change in beta 4 with how it was compiled. So, if you had an old beta installed and then it updated, chances are it’ll nag you to install .NET 6 because it’s missing .NET 6 dependencies. Installing the full setup should fix that because it’ll install the missing files without requiring you to install .NET 6 framework; future auto updates should then work for you.

**Comment by SpyrosTTK** [comment]
Thanks a lot fixed!

btw any way of retaining profiles, without exporting them and saving them somewhere? I was working on the ATIS profiles on version 8 a bit. Not too much work lost though.

**Comment by justinshannon** [comment]
What data did you lose after upgrading from beta 8 to beta 9?

**Comment by justinshannon** [comment]
No, the only way to save them is to export them.
