### ISSUE TITLE
No Wind shown in raw data output 

### ISSUE THREAD

**Issue by fcooper94** [vatis-project/vatis#42]
![image](https://user-images.githubusercontent.com/16825107/169281475-dd650409-2209-4ef5-9e17-85fa2a6dc803.png)

![image](https://user-images.githubusercontent.com/16825107/169281507-9cba1187-8a39-48ca-9582-d711eac4f56c.png)

Just showing TL and Varying directions not actual wind direction and stregnth.

**Comment by justinshannon** [comment]
Please provide a full METAR and composite configuration file.

**Comment by mythicfci** [comment]
I can confirm I'm having the same issue with vATIS not showing the wind information in the text ATIS (even though it is spoken out loud as usual). See the image below:
![image](https://user-images.githubusercontent.com/49729038/169679142-1e6955b3-1a6b-4e5d-aff6-9ac1b9917671.png)

Also attached is my vATIS profile for reference (in a ZIP file so that GitHub will allow it to be uploaded).
[vATIS Profile - Reykjavik CTA (BIRD).zip](https://github.com/vatis-project/vatis/files/8748773/vATIS.Profile.-.Reykjavik.CTA.BIRD.zip)
.

**Comment by TheAlphaFlyer** [comment]
can confirm as well. Will not show the winds. 
![image](https://user-images.githubusercontent.com/43100687/170034657-2256dd95-59af-4761-aa6b-13558424747d.png)

**Comment by mythicfci** [comment]
Follow up:
![image](https://user-images.githubusercontent.com/49729038/171051498-62b800b7-cbdd-49a2-a5fd-c88368e4c048.png)
It seems like _variable_ winds are included, but the winds themselves are not.

**Comment by chrissKLO** [comment]
Getting the same issues in OBBB/OMAE/OOMM FIR profiles. No winds despite the string being attached. Variable winds are included only.

**Comment by mythicfci** [comment]
Beta 3 fixes this issue
