### ISSUE TITLE
vAtis 4.0.0.2 will not load on Windows 7

### ISSUE THREAD

**Issue by githubvatsim** [vatis-project/vatis#51]
Program will not run on Windows 7.

Thanks.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	vATIS.exe
  Application Version:	4.0.0.2
  Application Timestamp:	62570982
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.17514
  Fault Module Timestamp:	4ce7c78c
  Exception Code:	e0434352
  Exception Offset:	000000000000a49d
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	80ef
  Additional Information 2:	80ef29f635b28d8ecc04aa1f0538255b
  Additional Information 3:	980c
  Additional Information 4:	980ca2c921b02dc20b971329c5585a14

**Comment by githubvatsim** [comment]
Sadly, installing the SDK does not seem to help. Same error message. I'm a Mac user running Windows 7 on a virtual platform just for Euroscope. Windows is a foreign country. Unable so far to find other Exception information. (The Windows firewall is off.
![InstallError](https://user-images.githubusercontent.com/51534154/170083655-82cb7372-33e1-4674-a276-1fc68e1d1e4f.jpg)
)

**Comment by collink2451** [comment]
My vATIS doesn't show up in Control Panel/Programs as well and looking at the installer it isn't set up to do so so that isn't an issue.

After you try launching it, go to the Event Viewer.
Under "Summary of Administrative Events" expand the Error section and look for a "Source" that says ".NET Runtime"
If it shows up double click on it and a new page should show up
On that page select the first error at the top and send a screenshot of the bottom section which should have the information as to why it is crashing.

**Comment by githubvatsim** [comment]
Superb instructions!
![ErrorCode](https://user-images.githubusercontent.com/51534154/170113602-891f48b5-29d5-4955-afb2-8c9cbafde938.jpg)

**Comment by collink2451** [comment]
I did some digging to see if I could find anything on this error and I was not able to find anyone else with a similar issue so it may be code related so I will have to defer to @justinshannon on this one.
Overall it looks like there are 2 separate issues that are causing this and it is not related to the SDK.
At least now we have more information so hopefully Justin can help you out and/or fix it in a future version.

**Comment by githubvatsim** [comment]
Thank you very much for giving your time to this issue.

**Comment by justinshannon** [comment]
Windows 7 is not supported.

**Comment by githubvatsim** [comment]
OK. Ticket closed.
