### ISSUE TITLE
ICAO/European Airports not written out by name anymore

### ISSUE THREAD

**Issue by gvert27** [vatis-project/vatis#58]
Even though "Format using FAA ATIS" is ticked "OFF" (not selected), the text ATIS is just displaysing the ICAO Code of the airport in Beta 2, instead of the airport name, which it did in Beta 1.

The ATIS below, would begin with "EDDK ATIS INFO..." instead of the correct reading, "Cologne/Bonn ATIS INFO..."

`[FACILITY] ATIS INFO [ATIS_CODE] MET REPORT TIME [OBS_TIME]. EXPECT ILS APPROACH RUNWAY 24. RUNWAY IN USE 24. ATTENTION! DEPARTURE FREQUENCY FOR ALL DEPARTING AIRCRAFT IS LANGEN RADAR ON 135.650 [TL]. [FULL_WX_STRING]. [NOTAMS]. [FACILITY] INFORMATION [ATIS_LETTER] OUT.`

**Comment by justinshannon** [comment]
The next version (not yet released) supports printing the voice string in the text ATIS for variables. In the template, you'll be able to use `[FACILITY:VOX]`, which will print the airport name (as read by voice) instead of the ICAO. 

`:VOX` can be appended to all available variables to print the voice string instead of the text string in the text ATIS.
